// redux/constants/orderConstants.ts

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL';

export const EDIT_ORDER_REQUEST = 'EDIT_ORDER_REQUEST';
export const EDIT_ORDER_SUCCESS = 'EDIT_ORDER_SUCCESS';
export const EDIT_ORDER_FAIL = 'EDIT_ORDER_FAIL';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';

export const CHANGE_ORDER_STATUS_REQUEST = 'CHANGE_ORDER_STATUS_REQUEST';
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS';
export const CHANGE_ORDER_STATUS_FAIL = 'CHANGE_ORDER_STATUS_FAIL';

// PayStore Status Check
export const CHECK_PAYSTORE_STATUS_REQUEST = 'CHECK_PAYSTORE_STATUS_REQUEST';
export const CHECK_PAYSTORE_STATUS_SUCCESS = 'CHECK_PAYSTORE_STATUS_SUCCESS';
export const CHECK_PAYSTORE_STATUS_FAIL = 'CHECK_PAYSTORE_STATUS_FAIL';
export const CLEAR_PAYSTORE_STATUS = 'CLEAR_PAYSTORE_STATUS';
