// singleProviderConstants.ts
export const FETCH_SINGLE_PROVIDER_REQUEST = 'FETCH_SINGLE_PROVIDER_REQUEST';
export const FETCH_SINGLE_PROVIDER_SUCCESS = 'FETCH_SINGLE_PROVIDER_SUCCESS';
export const FETCH_SINGLE_PROVIDER_FAIL = 'FETCH_SINGLE_PROVIDER_FAIL';
export const CLEAR_SINGLE_PROVIDER = 'CLEAR_SINGLE_PROVIDER';




// redux/constants/paystoreConstants.ts
export const FETCH_PAYSTORE_OPERATORS_REQUEST = 'FETCH_PAYSTORE_OPERATORS_REQUEST';
export const FETCH_PAYSTORE_OPERATORS_SUCCESS = 'FETCH_PAYSTORE_OPERATORS_SUCCESS';
export const FETCH_PAYSTORE_OPERATORS_FAIL = 'FETCH_PAYSTORE_OPERATORS_FAIL';
export const CLEAR_PAYSTORE_OPERATORS = 'CLEAR_PAYSTORE_OPERATORS';
export const SELECT_PAYSTORE_GROUP = 'SELECT_PAYSTORE_GROUP';
export const SELECT_PAYSTORE_OPERATOR = 'SELECT_PAYSTORE_OPERATOR';
export const FETCH_PAYSTORE_PRODUCTS_BY_FIRM_REQUEST = 'FETCH_PAYSTORE_PRODUCTS_BY_FIRM_REQUEST';
export const FETCH_PAYSTORE_PRODUCTS_BY_FIRM_SUCCESS = 'FETCH_PAYSTORE_PRODUCTS_BY_FIRM_SUCCESS';
export const FETCH_PAYSTORE_PRODUCTS_BY_FIRM_FAIL = 'FETCH_PAYSTORE_PRODUCTS_BY_FIRM_FAIL';
